name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2024-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Grant execute permission
        run: chmod +x gradlew
      - name: find gradlew
        run: find . -name "gradlew"
      - name: Install dos2unix
        run: sudo apt-get Install -y dos2unix
      - name: Convert line endings
        run: dos2unix gradlew
      - name: Build robot code
        run: ./gradlew build
